version: 1.0.{build}
skip_branch_with_pr: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 6FPMYKoVDcoVomnYN48LYNtA9BF1A8wjzq+QDpSXhaw1qVvNUJ9JXmTNSLZ7u/Xk
  on:
    branch: master
    appveyor_repo_tag: true