version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore CompiledFilters.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: '**/CompiledFilters.nupkg'
  name: CompiledFilters.nupkg
- path: '**/CompiledFilters.symbols.nupkg'
  name: CompiledFilters.symbols.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 6FPMYKoVDcoVomnYN48LYNtA9BF1A8wjzq+QDpSXhaw1qVvNUJ9JXmTNSLZ7u/Xk
  on:
    appveyor_repo_tag: true