version: 1.0.{build}
max_jobs: 1
image: Visual Studio 2017
skip_branch_with_pr: true
before_build:
  - nuget restore CompiledFilters.sln
build:
  project: CompiledFilters.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 6FPMYKoVDcoVomnYN48LYNtA9BF1A8wjzq+QDpSXhaw1qVvNUJ9JXmTNSLZ7u/Xk
  on:
    appveyor_repo_tag: true