version: CI-Build-{build}
max_jobs: 1
image: Visual Studio 2017
before_build:
  - nuget restore CompiledFilters.sln
build:
  project: CompiledFilters.sln
  publish_nuget: true
  verbosity: normal
after_build:
  - cmd: cd CompiledFilters.Tests
  - cmd: dotnet test
test: off
nuget:
  disable_publish_on_pr: true
deploy:
  - provider: NuGet
    api_key:
      secure: 
    on:
      branch: master
      appveyor_repo_tag: true

for:

-
  branches:
    only:
      - master

  configuration: Release

-
  branches:
    except:
      - master

  configuration: Debug
  build:
    publish_nuget_symbols: true
